### ISSUE TITLE
Icons on Gnome 40 are in low resolution.

### ISSUE THREAD

**Issue by CleoMenezes** [b1izzard-34/Skeuo-icon-theme#12]
![image](https://user-images.githubusercontent.com/54215258/121272170-49de8680-c893-11eb-9ddf-b8b1ea05e645.png)

**Comment by TheCultLeader666** [comment]
Duplicate of #1

**Comment by CleoMenezes** [comment]
Sorry to open so many Issues. I really liked your icons. I want to start using them as soon as possible. I hope you find this a way to help.

**Comment by TheCultLeader666** [comment]
If you happened to be talking to me, not my icons, just an enthusiastic community member
