### ISSUE TITLE
[Icon Request] Microsoft Teams and BlueJ

### ISSUE THREAD

**Issue by maydayv7** [b1izzard-34/Skeuo-icon-theme#13]
Please add these icons:
![Teams](https://user-images.githubusercontent.com/73811274/113152224-89657280-9253-11eb-9954-12e0353845e0.png)
![BlueJ](https://user-images.githubusercontent.com/73811274/113155433-a3ed1b00-9256-11eb-8842-1256280769d5.png)

**Comment by b1izzard-34** [comment]
Done with the icons ... will push in a bunch :)

**Comment by maydayv7** [comment]
Thanks a lot!!
