### ISSUE TITLE
Icons seem too large

### ISSUE THREAD

**Issue by TheCultLeader666** [b1izzard-34/Skeuo-icon-theme#6]
The icons currently have no padding, putting them uncomfortably close to the active dot in the dash, and are visually bigger than similar Adwaita icons:
![image](https://user-images.githubusercontent.com/65368815/121239668-885e4c00-c867-11eb-9149-39cb630dbf10.png)
![image](https://user-images.githubusercontent.com/65368815/121239697-914f1d80-c867-11eb-8892-6d8d67f8c203.png)
![image](https://user-images.githubusercontent.com/65368815/121239745-a1ff9380-c867-11eb-802d-24f9a2edd7d8.png)

**Comment by b1izzard-34** [comment]
Thank you for mentioning that !! I will make sure to add some padding to the icons!!

**Comment by b1izzard-34** [comment]
@TheCultLeader666 Reduced the size of the icons by 10%. I think that would resolve the issue.

**Comment by b1izzard-34** [comment]
@TheCultLeader666 Reduced the size of the icons by 10 %. That resolved the issue!
